export default {
  loadMore: false,
  dataLoader: false,
  loader: false,
  partnersData: [],
  totalPartners: 0,

  statusModal:false,

  partnerPermissionData:[],

  accountId: null,
  city: null,
  createdAt: null,
  firmAddress: null,
  firmEmail: null,
  firmName: null,
  firmShort: null,
  gstDetail: null,
  id: null,
  logo: null,
  logoName: null,
  natureOfBusiness: null,
  ownerEmail: null,
  ownerMobile: null,
  ownerName: null,
  ownerWhatsApp: null,
  pincode: null,
  settingId: null,
  singleMultiType:null,
  state: null,
  status: null,
  updatedAt: null,
  updatedId: null,
  website: null,
};

