export const borderOptions = [
  { name: "0px solid" },
  { name: "1px solid" },
  { name: "2px solid" },
  { name: "3px solid" },
  { name: "4px solid" },
  { name: "5px solid" },
  { name: "6px solid" },
  { name: "7px solid" },
  { name: "8px solid" },
  { name: "9px solid" },
];

export const radiusOptions = [
  { name: "0px" },
  { name: "1px" },
  { name: "2px" },
  { name: "3px" },
  { name: "4px" },
  { name: "5px" },
  { name: "6px" },
  { name: "7px" },
  { name: "8px" },
  { name: "9px" },
  { name: "10px" },
  { name: "11px" },
  { name: "12px" },
  { name: "13px" },
  { name: "14px" },
  { name: "15px" },
  { name: "16px" },
  { name: "17px" },
  { name: "18px" },
  { name: "19px" },
];
