export const fontList = [
  { name: "Roboto, sans-serif" },
  { name: "Zilla Slab Highlight, cursive" },
  { name: "Open Sans, sans-serif" },
  { name: "Spectral, serif" },
  { name: "Slabo 27px, serif" },
  { name: "Lato, sans-serif" },
  { name: "Roboto Condensed, sans-serif" },
  { name: "Oswald, sans-serif" },
  { name: "Source Sans Pro, sans-serif" },
  { name: "Raleway, sans-serif" },
  { name: "Zilla Slab, serif" },
  { name: "Montserrat, sans-serif" },
  { name: "PT Sans, sans-serif" },
  { name: "Roboto Slab, serif" },
  { name: "Merriweather, serif" },
  { name: "Saira Condensed, sans-serif" },
  { name: "Saira, sans-serif" },
  { name: "Open Sans Condensed, sans-serif" },
  { name: "Saira Semi Condensed, sans-serif" },
  { name: "Saira Extra Condensed, sans-serif" },
  { name: "Julee, cursive" },
  { name: "Archivo, sans-serif" },
  { name: "Ubuntu, sans-serif" },
  { name: "Lora, serif" },
  { name: "Manuale, serif" },
  { name: "Asap Condensed, sans-serif" },
  { name: "Faustina, serif" },
  { name: "Cairo, sans-serif" },
  { name: "Playfair Display, serif" },
  { name: "Droid Serif, serif" },
  { name: "Noto Sans, sans-serif" },
  { name: "PT Serif, serif" },
  { name: "Droid Sans, sans-serif" },
  { name: "Arimo, sans-serif" },
  { name: "Poppins, sans-serif" },
  { name: "Sedgwick Ave Display, cursive" },
  { name: "Titillium Web, sans-serif" },
  { name: "Muli, sans-serif" },
  { name: "Sedgwick Ave, cursive" },
  { name: "Indie Flower, cursive" },
  { name: "Mada, sans-serif" },
  { name: "PT Sans Narrow, sans-serif" },
  { name: "Noto Serif, serif" },
  { name: "Bitter, serif" },
  { name: "Dosis, sans-serif" },
  { name: "Josefin Sans, sans-serif" },
  { name: "Inconsolata, monospace" },
  { name: "Bowlby One SC, cursive" },
  { name: "Oxygen, sans-serif" },
  { name: "Arvo, serif" },
  { name: "Hind, sans-serif" },
  { name: "Cabin, sans-serif" },
  { name: "Fjalla One, sans-serif" },
  { name: "Anton, sans-serif" },
  { name: "Cairo, sans-serif" },
  { name: "Playfair Display, serif" },
  { name: "Droid Serif, serif" },
  { name: "Noto Sans, sans-serif" },
  { name: "PT Serif, serif" },
  { name: "Droid Sans, sans-serif" },
  { name: "Arimo, sans-serif" },
  { name: "Poppins, sans-serif" },
  { name: "Sedgwick Ave Display, cursive" },
  { name: "Titillium Web, sans-serif" },
  { name: "Muli, sans-serif" },
  { name: "Sedgwick Ave, cursive" },
  { name: "Indie Flower, cursive" },
  { name: "Mada, sans-serif" },
  { name: "PT Sans Narrow, sans-serif" },
  { name: "Noto Serif, serif" },
  { name: "Bitter, serif" },
  { name: "Dosis, sans-serif" },
  { name: "Josefin Sans, sans-serif" },
  { name: "Inconsolata, monospace" },
  { name: "Bowlby One SC, cursive" },
  { name: "Oxygen, sans-serif" },
  { name: "Arvo, serif" },
  { name: "Hind, sans-serif" },
  { name: "Cabin, sans-serif" },
  { name: "Fjalla One, sans-serif" },
  { name: "Anton, sans-serif" },
  { name: "Acme, sans-serif" },
  { name: "Archivo Narrow, sans-serif" },
  { name: "Mukta Vaani, sans-serif" },
  { name: "Play, sans-serif" },
  { name: "Cuprum, sans-serif" },
  { name: "Maven Pro, sans-serif" },
  { name: "EB Garamond, serif" },
  { name: "Passion One, cursive" },
  { name: "Ropa Sans, sans-serif" },
  { name: "Francois One, sans-serif" },
  { name: "Archivo Black, sans-serif" },
  { name: "Pathway Gothic One, sans-serif" },
  { name: "Exo, sans-serif" },
  { name: "Vollkorn, serif" },
  { name: "Libre Franklin, sans-serif" },
  { name: "Crete Round, serif" },
  { name: "Alegreya, serif" },
  { name: "PT Sans Caption, sans-serif" },
  { name: "Alegreya Sans, sans-serif" },
  { name: "Source Code Pro, monospace" },
];
