export default {
  loadMore: false,
  dataLoader: false,
  loader: false,
  loaderButton: false,

  sidebarVisible: false,

  otpStatus: false,
  regOtpStatus: false,
  submitSuccessStatus: false,
  statusModal: false,
  menuActive: false,
  forgotOtpStatus:false,
  forgotPasswordStatus:false,


  permissiondata: [],
  staffDocument: [],

  account: null,
  accountId: null,
  address: null,
  canteen: null,
  cast: null,
  city: null,
  contactNo: null,
  createdAt: null,
  designationId: null,
  dob: null,
  emailId: null,
  gender: null,
  guardianContactNo: null,
  guardianIncome: null,
  guardianName: null,
  guardianOccupation: null,
  guardianRelation: null,
  hostel: null,
  id: null,
  joiningDate: null,
  library: null,
  name: null,
  nationality: null,
  pincode: null,
  profile: null,
  profileName: null,
  religion: null,
  rfidNo: null,
  spouseContactNo: null,
  spouseIncome: null,
  spouseName: null,
  spouseOccupation: null,
  state: null,
  status: null,
  transport: null,
  updatedAt: null,
  updatedBy: null,
};
