
export default {
  loadMore: false,
  dataLoader: false,
  loader: false,
  loaderButton: false,

  branchStaffData: [],
  totalBranchStaff: 0,

  staffList: [],

  permissiondata: [],
  staffDocument: [],
  staffTimeTable: [],

  branchStaffModal: false,
  confirmModal: false,
  statusModal: false,
  addClassModal: false,
  addDepartmentModal: false,
  confirmDepartmentModal: false,
  addDivisionModal: false,
  confirmDivisionModal: false,
  addSubjectModal: false,
  confirmSubjectModal: false,
  addDocModal: false,
  confirmDocModal: false,
  docStatusModal: false,
  orderModal: false,

  account: null,
  accountId: null,
  address: null,
  canteen: null,
  cast: null,
  city: null,
  contactNo: null,
  createdAt: null,
  designationId: null,
  designation: null,
  dob: null,
  emailId: null,
  gender: null,
  guardianContactNo: null,
  guardianIncome: null,
  guardianName: null,
  guardianOccupation: null,
  guardianRelation: null,
  hostel: null,
  id: null,
  joiningDate: null,
  library: null,
  name: null,
  nationality: null,
  organizationDetailId: null,
  organizationDetail: null,
  pincode: null,
  profile: null,
  profileName: null,
  religion: null,
  rfidNo: null,
  spouseContactNo: null,
  spouseIncome: null,
  spouseName: null,
  spouseOccupation: null,
  state: null,
  status: null,
  transport: null,
  updatedAt: null,
  updatedBy: null,
  staffClass: [],
  staffDepartment: [],
  staffDivision: [],
  staffDocument: [],
  staffSubject: [],
  classListDiv: [],
  coOrdinator: [],
};
