
export default {
  loadMore: false,
  dataLoader: false,
  loader: false,
  loaderButton: false,

  bookData:[],
  totalBook:0,

  libraryModal: false,
  fileUploadModal:false,
  confirmModal: false,
  statusModal: false,

  accountId: null,
  address: null,
  admissionNo: null,
  canteen: null,
  cast: null,
  city: null,
  classDivId: null,
  classListId: null,
  contactNo: null,
  createdAt: null,
  dob: null,
  emailId: null,
  fatherContactNo: null,
  fatherIncome: null,
  fatherName: null,
  fatherOccupation: null,
  gender: null,
  hostel: null,
  houseZoneId: null,
  id: null,
  library: null,
  motherContactNo: null,
  motherIncome: null,
  motherName: null,
  motherOccupation: null,
  name: null,
  nationality: null,
  organizationDetailId: null,
  pincode: null,
  profile: null,
  profileName: null,
  regNo: null,
  religion: null,
  rfidNo: null,
  rollNo: null,
  settingId: null,
  state: null,
  status: null,
  stream: null,
  studentNo: null,
  transport: null,
  updatedAt: null,
  updatedId: null,
};
